# Generated by Django 2.1.15 on 2023-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230913_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
