# Generated by Django 2.1.15 on 2023-09-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
