# Generated by Django 2.1.15 on 2023-10-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
